swagger: "2.0"
info:
  version: "0.0.1"
  title: CryptoStockZ Service
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user:
    x-swagger-router-controller: cryptostockz.controller
    get:
      description: Returns a user by name, password
      tags:
        - users
      operationId: getUserId
      produces:
        - application/json
      parameters:
        - name: userData
          in: body
          required: true
          description: Users data in JSON format.
          schema:
            type: object
            required:
              - userName
              - userPass
            properties:
              userName:
                type: string
              userPass:
                type: string
      responses:
        '200':
          description: OK
    post:
      description: Creates a new user
      tags:
        - users
      operationId: createUser
      produces:
        - application/json
      parameters:
        - name: userData
          in: body
          required: true
          description: Users data in JSON format.
          schema:
            type: object
            required:
              - userName
              - userPass
            properties:
              userName:
                type: string
              userPass:
                type: string
      responses:
        "200":
          description: Success
          schema: {}
        default:
          description: Error
          schema: {}

  /test:
    x-swagger-router-controller: cryptostockz.controller
    get:
      description: Returns a test message
      tags:
        - test
      operationId: getTest
      produces:
        - application/json
      responses:
        "200":
          description: Success
          schema: {}
        default:
          description: Error
          schema: {}
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
